# Generated by Django 3.1.1 on 2020-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0002_auto_20201129_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='vsrun.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
