# Generated by Django 3.1.1 on 2020-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0003_products_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='phone',
        ),
    ]
