# Generated by Django 3.1.1 on 2020-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0004_auto_20201129_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Employee',
        ),
    ]
