# Generated by Django 3.1.1 on 2020-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0005_auto_20201129_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='gfhgfhg', max_length=200),
            preserve_default=False,
        ),
    ]
